name: neubrutal_kit
description: "A modern Flutter package providing neubrutalism-styled UI components for creating distinctive, playful interfaces with bold shadows and vivid colors."
version: 0.0.2
repository: https://github.com/Mani821/neubrutal_kit
issue_tracker: https://github.com/Mani821/neubrutal_kit/issues
homepage: https://github.com/Mani821/neubrutal_kit

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons/close.png
